---
repository:
  name: github-action-continuous-release-test
  description: My personal ansible setup for my workstations and servers.
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_pages: false
  has_downloads: false

  is_template: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: true
  delete_branch_on_merge: true

  allow_forking: true

  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
# Start PR labels
  - name: breaking
    color: D93F0B
    description: Breaking change

  - name: feature
    color: 0E8A16
    description: A new feature

  - name: fix
    color: B60205 # TODO colour
    description: A bug fix

  - name: documentation
    color: 0052CC
    description: Improvements or additions to documentation

  - name: refactor
    color: 0052CC # TODO colour
    description: A code change that neither fixes a bug nor adds a feature

  - name: performance
    color: 0052CC # TODO colour
    description: A code change that improves performance

  - name: test
    color: 0052CC # TODO colour
    description: Adding missing tests or correcting existing tests

  - name: build
    color: 0052CC # TODO colour
    description: "Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)"

  - name: ci
    color: 0052CC # TODO colour
    description: "Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)"

  - name: released
    color: 0052CC # TODO colour
    description: Released by Semantic Release

# End PR labels

  - name: semantic-release
    color: 0052CC # TODO colour
    description: Issue created by Semantic Release

  - name: feature-request
    color: 0E8A16
    description: A feature request

  - name: bug
    color: B60205
    description: Something isn't working

  - name: duplicate
    color: CFD3D7
    description: This issue or pull request already exists

  - name: good first issue
    color: 7057FF
    description: Good for newcomers

  - name: help
    color: 008672
    description: Extra attention is needed

  - name: question
    color: D876E3
    description: Further information is requested

  - name: stale
    color: FBCA04
    description: A stale issue or pull request

  - name: invalid
    color: FFFFFF
    description: This doesn't seem right

  - name: wontfix
    color: FFFFFF
    description: This will not be worked on

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts:
          - Test / Test
          - Validate branch name
          - Validate PR title
          - Label PR
      enforce_admins: false
      required_linear_history: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: false
