---
name: Pull Request
"on":
  pull_request: # TODO check trigger
    branches: [main]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  # TODO should this be named better (lint-branch-name?)
  check-branch-name:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: ^[a-z]+\/([a-z]|-)+$ # TODO what should this regex be? Prefixes or not?
          allowed_prefixes: break,feat,bug,chore,docs

  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}" didn't match the configured pattern.
            Please ensure that the subject doesn't start with an uppercase character.

  # TODO names for steps
  # TODO maybe don't bother with this
#  check-commits:
#    name: Check commits
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Check commits
#        uses: aevea/commitsar@v0.18.0

  label:
    name: Label
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: bcoe/conventional-release-labels@v1.3.0



#  label:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: TimonVS/pr-labeler-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
