---
name: Pull Request
"on":
  pull_request: # TODO check trigger
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  # TODO should this be named better (lint-branch-name?)
  check-branch-name:
    name: Check branch name
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: ^[a-z]+\/([a-z]|-)+$ # TODO what should this regex be? Prefixes or not?
          allowed_prefixes: break,feat,bug,chore,docs

  check-pr-title:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}" didn't match the configured pattern.
            Please ensure that the subject doesn't start with an uppercase character.

#  label:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: TimonVS/pr-labeler-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
