---
name: Scan

"on":
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0 editorconfig-checker-disable-line

      - name: Initialize CodeQL
        # yamllint disable-line rule:line-length
        uses: github/codeql-action/init@1ed1437484560351c5be56cf73a48a279d116b78 # tag=v2.1.8 editorconfig-checker-disable-line
        with:
          languages: javascript, java

      # - name: Autobuild
      # uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        # yamllint disable-line rule:line-length
        uses: github/codeql-action/analyze@1ed1437484560351c5be56cf73a48a279d116b78 # tag=v2.1.8 editorconfig-checker-disable-line
